### ISSUE TITLE
@Delegate adds duplicate interface

### ISSUE THREAD

**Issue by stevenroose** [a14n/zengen#23]
If an implementing interface is already defined that is later also implemented using @Delegate on an object with that interface, the generator adds it to the class declaration as a duplicate causing an error.

**Comment by a14n** [comment]
I usually avoid to put `implements` on the template overwise the analyzer complains about _missing concrete implementation_ in the template class.
But I agree it shouldn't add the implements part if it's already there.

**Comment by a14n** [comment]
After looking back at the code you can also use `@Delegate(addImplements:false)` if you prefer to put the implements clause manually on the template class.
