### ISSUE TITLE
Static variabled are also implemented with @Delegate

### ISSUE THREAD

**Issue by stevenroose** [a14n/zengen#25]
The @Delegate also adds the static variables of the delegated class to the class. 

This results in the following warming from the Dart Analyzer:
```
[warning] Static member 'XX_XX' cannot be accessed using instance access (xx.g.dart, line x, col x)
```

**Comment by stevenroose** [comment]
You are awesome!

On Tue, Dec 15, 2015 at 3:50 PM, Alexandre Ardhuin <notifications@github.com

**Comment by a14n** [comment]
Version 0.3.1 is published. Thanks for the issue reports.
