### ISSUE TITLE
Add an annotation to specify the desired location for the generated files.

### ISSUE THREAD

**Issue by stevenroose** [a14n/zengen#28]
I don't want `.g.dart` files directly in the `lib/` folder of a package. If I want to keep the source code in that folder, currently I have to move the generated files manually every time after generation.

F.e. 
```dart
@Zengen(location: "src/")
class _SomeClass {}
```

If the location is a folder, use the same filename as currently, `file.g.dart`. If the location is a full path with file name, just use that part as the generated file.

Requiring an annotation for each class that needs generation would solve #24, but I'm not sure if requiring the annotation is preferable.

**Comment by a14n** [comment]
_zengen_ relies on _source_gen_ for the creation of `.g.dart` file. You should move this issue to [source_gen](https://github.com/dart-lang/source_gen/issues).

**Comment by stevenroose** [comment]
https://github.com/dart-lang/source_gen/issues/76
